#we use java
language: java

#we add the java development kit (jdk)
jdk:
- openjdk8
services:
#Linking Travis CI and Docker
- docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk-alpine

addons:
  sonarcloud:
    organization: "cicd-applied-to-spring-boot-java-app-ccizer"
    token:
      secure: "GkSzHoqu+9lDVEE8piQFhWbdPq+p3K1FqNm8irRAZOnsgHYdzMCvOPw0KTMoYXzYNjdy1ug8nSjfOx5T1z9ZUx6p2gFbT8vtyiMatbukVdWOGK9jlR0MJ6YqHTuYx04j/T+X0aZsMc45pDlRpf5u+t+PA5JY7W6kwioO9IhUBeDvIoW/DUEGPi/oyKfpel3dbVBc5E184VNa6MvHsKfaEZkc8nTTJS5sZC4//7TiHGM3E1DgdAh22/daIJKb6d0fOSrquT66lkB3YYf06LtJUCU566vnSIY7/Y0rfesd1jm/nqbAarx6IN0bcYOYowBW3sOI13DARG5KMzxEenQXN7McVVIy3fuL/F0aghDjfjEWDgwAHM6Mtgm+SSKkyzbRY5UQUpqEiVxzdICldoRFZIEVGPSKekZNqoNo5X5bcfxO3Hfm43pzJoBsPxpzMiIsCzWgvc9EjZFQgE6JvtQG8CYHmRK5BqOO8TsiFK5z2AwZMbTp3AsFWynTp0++NSnkl/8Heyp0lYSpqlstxIs7bVWDV+qoto4sC1DyfOCTlkTtXxHqgnKNi5KPsqZF/3tT766iFvdzbolBuXsjw1re6nBvGpRGBOA38BNyO8xVkoVay9LOmOqgXy15AwfgoJ78RLOm9picKak3haqBa/VJJbZbWoF5P4ZrDvDYMAuDzFo="

script:
#We avoid this error :" the job exceeded the maximum log length and has been terminated "
- echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
- cat $HOME/.m2/settings.xml
# Deploy to Docker
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
- bash <(curl -s https://codecov.io/bash)
