#we use java
language: java

#we add the java development kit (jdk)
jdk:
- openjdk8
services:
#Linking Travis CI and Docker
- docker

before_install:
- echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
- docker pull openjdk:8-jdk-alpine

addons:
  sonarcloud:
    organization: "com-ccizer-project"
    token:
      secure: "ntUPp1EEr8dwlbJXvfSQRd6HR18qylgnD4+F09ACGX9mgbNXKrHtWZC3HbRihBDtSyKcfXXJuGXnRJRpTx173VfxE/V2fiqRjMHAR0r7UeNGh5IuZPeYih6aRqsS+BAjh3ujgHNIeAaWgIZbunUqBH6p0jnvYmdO+luqsv5cSl4s7+MC8f/xfF0nGTDYw3Qceeoqb4ZID0AE9mo/1507HRv8VlB0AdoH0jxPsAe48t0lFfVcthwcFCWHO+VjNJZifCI3pxbH07a8Rv9O89oFJhi3RZYnmH0HZanHnexQy4yHCx4V3oZ7zz1sEDO+tqVOt2QxPOfMbdWP/dkgYYkV+pxw85c1dT9I2HRm2PY0dnKEBm2KCIE+7KfRiPcwJ7HFOYFIITeE1dsu6R3/sn4rJ0/Pb9VxWuTToY+tfYYkSC45lI/ukUPcbMMSTdbmicalWOzdeFP0hB25U80YrfxGogOLAsUwEMyyMAgl5mQ61p0JXvJggu6e6uTWNRESUC1p13Iw2XSxvyBNEc9jjldDBD4wdfucxyvkaVxr3dL3LsVApfufak0984rngnqvhNru8LUBrri/rc043S770A11B9zFfKcoPP4Rn0Kn9mxDSm7/b86Ke3FZndsREDcc/pVUCfg3A7R5Wmb9WPuDPd2Fp6RX/wuatpHIjPgyPEkDRs0="

script:
#We avoid this error :" the job exceeded the maximum log length and has been terminated "
- echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
- cat $HOME/.m2/settings.xml
# Deploy to Docker
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ccizer_cicd-applied-to-spring-boot-java-app
#deploying the app on Docker & Heroku
- echo "$HEROKU_TOKEN" | docker login --username=_ --password-stdin registry.heroku.com
- docker tag $DOCKER_IMAGE:latest registry.heroku.com/$YOUR_APP_NAME/web
- docker push registry.heroku.com/$YOUR_APP_NAME/web
- heroku container:release web --app $YOUR_APP_NAME

after_success:
# Codecov integration
- bash <(curl -s https://codecov.io/bash)
# Assertible API Monitor Trigger URL
- |
  curl -u $ASSERTIBLE_TOKEN: -XPOST "https://assertible.com/deployments" -d'{
          "service": "'"${ASSERTIBLE_SERVICE}"'",
          "environmentName": "'"production"'",
          "version": "'"v1"'"
  }'
